name: Create Tag Release

on:
    push:
        branches:
            - "master"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # --------------------------------
            # コードのチェックアウト
            # --------------------------------
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # --------------------------------
            # .NETのセットアップ
            # --------------------------------
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            # --------------------------------
            # バージョンの確認
            # --------------------------------
            - name: Get Version
              shell: bash
              run: |
                  VERSION=$(cat .version | tr -d '[:space:]')
                  echo VERSION=$VERSION > ${GITHUB_ENV}
                  echo "TAG_NAME=Ver.$VERSION" >> ${GITHUB_ENV}

            # --------------------------------
            # タグ名の確認
            # --------------------------------
            - name: Check Tag Name
              shell: bash
              run: |
                  if git rev-parse "refs/tags/${{ env.TAG_NAME }}" >/dev/null 2>&1; then
                      echo "Tag ${{ env.TAG_NAME }} already exists."
                      exit 1
                  fi

            # --------------------------------
            # レストア
            # --------------------------------
            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: |
                  dotnet build \
                  --no-restore \
                  --configuration Release

            # -------------------------
            # 発行
            # -------------------------
            - name: Publish
              run: |
                  dotnet publish \
                  src/lib/IOExpansionsLib/IOExpansionsLib.csproj \
                  --configuration Release \
                  --no-restore \
                  --output ./publish \
                  -p:Version=${{ env.VERSION }} \
                  -p:FileVersion=${{ env.VERSION }}

            # --------------------------------
            # ZIP 圧縮
            # --------------------------------
            - name: Create ZIP
              run: |
                  cd publish
                  zip -r \
                      "../IOExpansionsLib_${{ env.VERSION }}.zip" \
                      .

            # --------------------------------
            # ZIP確認
            # --------------------------------
            - name: Check ZIP
              run: |
                  ls -lh
                  test -f "IOExpansionsLib_${{ env.VERSION }}.zip"

            # -------------------------
            # git 設定
            # -------------------------
            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            # -------------------------
            # タグ作成
            # -------------------------
            - name: Create Tag
              run: |
                  git tag -a "${{ env.TAG_NAME }}" -m "Release ${{ env.VERSION }}"
                  git push origin "${{ env.TAG_NAME }}"

            # --------------------------------
            # GitHub Release 作成
            # --------------------------------
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  name: Release ${{ env.VERSION }}
                  generate_release_notes: true
                  files: |
                      ./IOExpansionsLib_${{ env.VERSION }}.zip
